Neos:
  Flow:
    persistence:
      doctrine:
        dbal:
          mappingTypes:
            'text_array':
              dbType: '_text'
              className: 'Doctrine\DBAL\PostgresTypes\TextArrayType'
    mvc:
      routes:
        'Sandstorm.OsqueryFleet.Core': true
    reflection:
      ignoredTags:
        'doc': TRUE

Sandstorm:
  OsqueryFleet:
    Core:
      enrollSecret: 'todo'
      alerting:
        rulePersistenceBackendOptions:
          user: sandstorm_readonly
          password: foo
