<?php
namespace Neos\Flow\Persistence\Doctrine\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration;
use Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your needs! This block will be used as the migration description if getDescription() is not used.
 */
class Version20180201154608 extends AbstractMigration
{

    /**
     * @return string
     */
    public function getDescription()
    {
        return '';
    }

    /**
     * @param Schema $schema
     * @return void
     */
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != 'postgresql', 'Migration can only be executed safely on "postgresql".');
        
        $this->addSql('CREATE TABLE sandstorm_osqueryfleet_core_domain_model_node (persistence_object_identifier VARCHAR(40) NOT NULL, hostidentifier VARCHAR(255) NOT NULL, nodekey VARCHAR(255) NOT NULL, hostname VARCHAR(255) NOT NULL, tags TEXT[] DEFAULT NULL, PRIMARY KEY(persistence_object_identifier))');
    }

    /**
     * @param Schema $schema
     * @return void
     */
    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != 'postgresql', 'Migration can only be executed safely on "postgresql".');
        
        $this->addSql('CREATE SCHEMA public');
        $this->addSql('DROP TABLE sandstorm_osqueryfleet_core_domain_model_node');
    }
}