<?php
namespace Neos\Flow\Persistence\Doctrine\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration;
use Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your needs! This block will be used as the migration description if getDescription() is not used.
 */
class Version20180204184922 extends AbstractMigration
{

    /**
     * @return string
     */
    public function getDescription()
    {
        return '';
    }

    /**
     * @param Schema $schema
     * @return void
     */
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != 'postgresql', 'Migration can only be executed safely on "postgresql".');
        
        $this->addSql('CREATE TABLE sandstorm_osqueryfleet_core_domain_model_query (persistence_object_identifier VARCHAR(40) NOT NULL, identifier VARCHAR(255) NOT NULL, name VARCHAR(255) NOT NULL, sqlquery TEXT DEFAULT NULL, interval INT NOT NULL, snapshot BOOLEAN NOT NULL, tags TEXT[] DEFAULT NULL, PRIMARY KEY(persistence_object_identifier))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_92098D8FAADCF14E ON sandstorm_osqueryfleet_core_domain_model_node (nodekey)');
    }

    /**
     * @param Schema $schema
     * @return void
     */
    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != 'postgresql', 'Migration can only be executed safely on "postgresql".');
        
        $this->addSql('CREATE SCHEMA public');
        $this->addSql('DROP TABLE sandstorm_osqueryfleet_core_domain_model_query');
        $this->addSql('DROP INDEX UNIQ_92098D8FAADCF14E');
    }
}